# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[merge] 
automerge_label = "ship it"
require_automerge_label = true
block_on_neutral_required_check_runs = true
blocking_labels = ["wip", "do not merge"]
delete_branch_on_merge = true
notify_on_conflict = true
optimistic_updates = false
prioritize_ready_to_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
body_type = "markdown"
include_pr_number = true
include_coauthors = true
include_pull_request_url = true
cut_body_after = "<!-- COMMIT_BODY_TEXT_BEGIN -->"
cut_body_before = "<!-- COMMIT_BODY_TEXT_END -->"

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" version upgrades.
# do not automerge "major" version upgrades.
versions = ["minor", "patch"]
usernames = ["dependabot", "renovate"]

[approve]
auto_approve_usernames = ["dependabot", "renovate"]

[update]
always = true
require_automerge_label = true
