# Versions and updates, dependabot.yml

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    # No one cares about dependency labels, they should be auto-merged
    labels: []
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    rebase-strategy: "auto"
    # reviewers: []
